name: Repository Events
#on: [push, pull_request, issues]
on:
    push:
      branches: 
        - main
        - "feature/*" # matches feature/feata doesnot match eature/feata/featue
        - "featuer/**" # also matches match eature/feata/featue
      branches-ignore:
        - develop
      tags:
        - v1.*
        - "!v1.1.1"   
      paths:
        - "**.js"   # when there is pushed in main  branch and file js
        - "!app"

    pull_request:
        types: [opened,assigned,reopened,synchronize]
    issues:
        types: [opened]    


jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3