name: Exxpresio and context

on: [push, pull_request, issues, workflow_dispatch]
run-name: "Tile for expression and context by @${{ github.actor}}, events: {{ github.events }}"

jobs:
    using-expression-and-context:
        runs-on: ubuntu-latest
        steps:
            - name: Expression
              id: expression
              run: |
                echo ${{ 1 }}
                echo ${{ 'This is string' }}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{ 1 > 2 }}
                echo ${{ true && false }}
                echo ${{ true || ( false && true) }}
            - name: Dump Contexts
              run: |
                  echo '${{ toJson(github) }}'    
                  echo '${{ toJson(job) }}' 
                  echo '${{ toJson(secrets) }}' 
                  echo '${{ toJson(steps) }}' 
                  echo '${{ toJson(runner) }}' 
