name: first workflow
on: [push]

jobs:
  run-shell-commands: # user defined job name
    runs-on: ubuntu-latest
    steps:
      - name: echo astring
        run: echo "hello world"
      - name: Multiline command 
        run: |
          node -v
          npm -v

  parellel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW version
        run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: run-shell-commands              
    steps:
      - name: echo a string
        run: Write-Output "test powershell"
      - name: error-setup
        run: donpt existsss