name: Resuabale workflow

on:
  workflow_call:
    outputs:
        date:
            description: date value
            value: ${{ jobs.generate-output.outputs.date }}
    
jobs:
    nested-workflow-call:
        uses: vikram0100/github-action2/.github/workflows/resuable.yaml@main
        with:
            name: 'bikram'
        secrets: 
            access-token: ${{ secrets.ACCESS_GITHUB_TOKEN }}    

    generate-output:
        runs-on: ubuntu-latest
        outputs:
            date: ${{ steps.date-step.outputs.date }}
        steps:
            - run: echo "date=$(date)" >> $GITHUB_OUTPUT
              id: date-step    