name: varabels and secrets
on: [push]

jobs:
    log-vars:
      runs-on: ${{ vars.RUNNER }}
      environment: 'staging'
      env:
        BOOLEAN_SECRET: ${{ secrets.REPOSITORY_SECRET }}
      steps:
        - name: Run only of boolean secret is true
          if: env.BOOLEAN_SECRET == 'true'
          run: echo "secret run"   
        - name: echo all the varibales
          run: |
            echo ${{ vars.REPOSITORY_VAR }}   
            echo ${{ vars.RUNNER }}    
            echo ${{ secrets.REPOSITORY_SECRET }} 
            echo ${{ vars.STAGING_ENV }}