name: Workflow commnads
on: [push]

jobs:
    testting-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: setting error message
              run:  echo "::error::Missing semicolon"
            - name: error message with param
              run: echo "::error title=Error title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"    
            - name: debug message with param
              run: echo "::debug title=Debug title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"  
            - name: warning message with param
              run: echo "::warning title=Warning title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"                              
            - name: Notice message with param
              run: echo "::notice title=Notice title,file=app.js,line=2,endLine=3,col=5,endColumn=7::Missing Semicolon"  
